ALTER TABLE dbo.T_TBLINVDETAILS ADD
	INVDET_PROMOCODE varchar(20) NULL
GO


---------------------------------------




ALTER PROCEDURE [dbo].[myPOS_DP_GET_INV_DETAILS]
	@invoiceNo varchar(max)
AS
BEGIN

            SELECT DISTINCT
			i.INVDET_INVNO INVOICE_NO
			,CONVERT(varchar,i.INVDET_DATETIME,126) AS DATE_TIME
			,'' TEMP_KEY
			,i.INVDET_SETUPLOC SETUP_LOCATION
			,i.INVDET_LINENO LINE_NO
			,i.INVDET_SALESMAN SALEMAN
			,i.INVDET_VOID ITEM_VOID
			,i.INVDET_PROCODE PRO_CODE
			,i.INVDET_STOCKCODE STOCK_CODE
			,i.INVDET_PRODESC POS_DESC
			,u.UM_CODE PRO_UNIT
			,i.INVDET_PROCASESIZE PRO_CASE_SIZE
			,i.INVDET_PROCOST PRO_COST
			,i.INVDET_PROSELLING PRO_SELLING
			,i.INVDET_PROAVGCOST PRO_AVG_COST
			,i.INVDET_PROSELLING SELLING 
			,i.INVDET_DISCPER DISC_PRE
			,i.INVDET_DISCAMT DISC_AMT
			,i.INVDET_BILLDISCPER BILL_DISC_PRE
			,i.INVDET_BILLDISCAMT BILL_DISC_AMT
			,i.INVDET_CASEQTY CASE_QTY 
			,i.INVDET_UNITQTY UNIT_QTY 
			,i.INVDET_CASERETQTY CASE_FREE_QTY
			,i.INVDET_UNITRETQTY UNIT_FREE_QTY
			,i.INVDET_AMOUNT AMOUNT 
			,i.INVDET_FREEQTY FREE_QTY
			,i.INVDET_NODISC NO_DISC
			,i.INVDET_SCANBARCODE SCAN_BARCODE 
			,i.INVDET_DISTYPE INVDET_DISTYPE
			,i.INVDET_ISVOUCHER IS_VOUCHER
			,p.PLU_MAXDISCPER MAXDISC_PER
			,p.PLU_MAXDISCAMT MAXDISC_AMT
			,'' LINE_REMARK
			,I.INVDET_PRICEMODE PRICE_MODE
			,i.INVDET_PROMODISCPER PROMO_DISCPER
			,I.INVDET_PROMODISCAMT PROMO_DISCAMT
			,I.INVDET_PROMOBILLDISCPER PROMO_BILLDISCPER
			,I.INVDET_PROMOCODE PROMO_CODE
			FROM T_TBLINVDETAILS i 
			INNER JOIN T_TBLINVHEADER h
			ON INVDET_LOCCODE=INVHED_LOCCODE AND INVDET_INVNO=INVHED_INVNO AND INVDET_MODE=INVHED_MODE
			LEFT JOIN M_TBLPROMASTER p
			ON i.INVDET_PROCODE= p.PLU_CODE
			LEFT JOIN M_TBLUNITS u
			ON u.UM_DESC=i.INVDET_PROUNIT
			where i.INVDET_INVNO=@invoiceNo AND h.INVHED_MODE='INV' AND h.INVHED_CANCELED=0  ORDER BY i.INVDET_LINENO  /*AND h.INVHED_INVOICED=1 */
END
GO


--------------------------


ALTER TABLE dbo.T_TBLINVDETAILS_HOLD ADD
	INVDET_PROMOCODE varchar(20) NULL
go


--------------------------------





ALTER PROCEDURE [dbo].[myPOS_DP_GET_HOLD_INV_DETAILS]
	@invoiceNo varchar(max)
AS
BEGIN

            SELECT DISTINCT
			i.INVDET_INVNO INVOICE_NO
			,CONVERT(varchar,i.INVDET_DATETIME,126) AS DATE_TIME
			,'' TEMP_KEY
			,i.INVDET_SETUPLOC SETUP_LOCATION
			,i.INVDET_LINENO LINE_NO
			,i.INVDET_SALESMAN SALEMAN
			,i.INVDET_VOID ITEM_VOID
			,i.INVDET_PROCODE PRO_CODE
			,i.INVDET_STOCKCODE STOCK_CODE
			,i.INVDET_PRODESC POS_DESC
			,u.UM_CODE PRO_UNIT
			,i.INVDET_PROCASESIZE PRO_CASE_SIZE
			,i.INVDET_PROCOST PRO_COST
			,i.INVDET_PROSELLING PRO_SELLING
			,i.INVDET_PROAVGCOST PRO_AVG_COST
			,i.INVDET_PROSELLING SELLING 
			,i.INVDET_DISCPER DISC_PRE
			,i.INVDET_DISCAMT DISC_AMT
			,i.INVDET_BILLDISCPER BILL_DISC_PRE
			,i.INVDET_BILLDISCAMT BILL_DISC_AMT
			,i.INVDET_CASEQTY CASE_QTY 
			,i.INVDET_UNITQTY UNIT_QTY 
			,i.INVDET_CASERETQTY CASE_FREE_QTY
			,i.INVDET_UNITRETQTY UNIT_FREE_QTY
			,i.INVDET_AMOUNT AMOUNT 
			,i.INVDET_FREEQTY FREE_QTY
			,i.INVDET_NODISC NO_DISC
			,i.INVDET_SCANBARCODE SCAN_BARCODE 
			,i.INVDET_DISTYPE INVDET_DISTYPE
			,i.INVDET_ISVOUCHER IS_VOUCHER
			,p.PLU_MAXDISCPER MAXDISC_PER
			,p.PLU_MAXDISCAMT MAXDISC_AMT
			,'' LINE_REMARK
			,I.INVDET_PRICEMODE PRICE_MODE
			,i.INVDET_PROMODISCPER PROMO_DISCPER
			,i.INVDET_PROMODISCAMT PROMO_DISCAMT
			,i.INVDET_PROMOBILLDISCPER PROMO_BILLDISCPER
			,i.INVDET_PROMOCODE PROMO_CODE
			FROM T_TBLINVDETAILS_HOLD i 
			INNER JOIN T_TBLINVHEADER_HOLD h
			ON INVDET_LOCCODE=INVHED_LOCCODE AND INVDET_INVNO=INVHED_INVNO AND INVDET_MODE=INVHED_MODE
			LEFT JOIN M_TBLPROMASTER p
			ON i.INVDET_PROCODE= p.PLU_CODE
			LEFT JOIN M_TBLUNITS u
			ON u.UM_DESC=i.INVDET_PROUNIT
			where i.INVDET_INVNO=@invoiceNo AND h.INVHED_MODE='INV' AND h.INVHED_CANCELED=0  ORDER BY i.INVDET_LINENO  
END
GO


----------------------------


ALTER TABLE dbo.M_TBLPROMOTION_GROUPS ADD
	PG_COMBOTYPE int NULL
GO


---------------------------------



ALTER PROCEDURE [dbo].[myPOS_DP_GET_PROMOTIONS]
	@loc varchar(5)
	,@comCode varchar(5)
AS
BEGIN
	set datefirst 1;
	
	DECLARE @day int

	SET @day = DATEPART(WEEKDAY, GETDATE())
	SELECT 
	   PRO_CODE
      ,PRO_DESC
      ,PRO_NARRATION
      ,PRO_PRINT
      ,PRO_GROUP
      ,PRO_STATUS
      ,PRO_STDATE
      ,PRO_ENDATE
      ,PRO_STTIME
      ,PRO_ENTIME
      ,PRO_DAYS
      ,PRO_ST_BILLNET
      ,PRO_EN_BILLNET
      ,PRO_COMPANYS
      ,PRO_BDAY
      ,PRO_BDFROM
      ,PRO_BDTO
      ,PRO_ANNIVERSARY
      ,PRO_MINPOINTBAL
      ,PRO_CUSLIMIT
      ,PRO_INCLUSIVEITEMS
      ,PRO_PRIORITY
      ,PRO_LOYALCUSTOMERS
	  ,PROL_LOCCODE,
	  PG_CODE
      ,PG_DESC
      ,PG_STATUS
      ,PG_OUTLET
      ,PG_EXCL_ACT
      ,PG_INCL_ACT
      ,PG_PSKUBID_ACT
      ,PG_GRPBID_ACT
      ,PG_DISCPER_ACT
      ,PG_DISCAMT_ACT
      ,PG_FSKUBID_ACT
      ,PG_TICKET_ACT
      ,PG_VOU_ACT
      ,PG_POINT_ACT
      ,PG_CUS_SPECIFIC
	  ,PG_INCL_ACT_QTY 
	  ,PG_INCL_ACT_VALUE 
	  ,PG_INCL_ACT_ITEM 
	  ,PG_INCL_ACT_COMBINATION
	  ,PG_EXCL_ACT_QTY
	  ,PG_EXCL_ACT_VALUE
	  ,PG_EXCL_ACT_ITEM
	  ,PG_EXCL_ACT_COMBINATION
	  ,inc.PROE_CUSGROUPS PROI_CUSGROUPS
      ,inc.PROE_SUPGROUPS PROI_SUPGROUPS
      ,'' PROI_ITEMBUNDLEGROUPS
      ,'' PROI_GROUPBUNDLEGROUPS
	  ,'' PROE_CUSGROUPS
      ,'' PROE_SUPGROUPS
      ,'' PROE_ITEMBUNDLEGROUPS
      ,'' PROE_GROUPBUNDLEGROUPS	  
	  --,inc.PROE_CUSGROUPS PROI_CUSGROUPS
   --   ,inc.PROE_SUPGROUPS PROI_SUPGROUPS
   --   ,inc.PROE_ITEMBUNDLEGROUPS PROI_ITEMBUNDLEGROUPS
   --   ,inc.PROE_GROUPBUNDLEGROUPS PROI_GROUPBUNDLEGROUPS
	  --,exc.PROE_CUSGROUPS PROE_CUSGROUPS
   --   ,exc.PROE_SUPGROUPS PROE_SUPGROUPS
   --   ,exc.PROE_ITEMBUNDLEGROUPS PROE_ITEMBUNDLEGROUPS
   --   ,exc.PROE_GROUPBUNDLEGROUPS PROE_GROUPBUNDLEGROUPS
	,ISNULL( gp.PG_CARD,0) PG_CARD
	 ,ISNULL( gp.PG_PAY_ACT,0) PG_PAY_ACT,
	 isnull(promo.PRO_SELECTABLE,0) as PRO_SELECTABLE
	 ,PG_EXCLUDE_INCLUSIVE
	 ,PG_VALIDQTY_CHECK_SKU
	 ,PG_DISCAMT_APPLY_TO_BILL
	 ,PG_TICKET_VALUE
	 ,PG_COUPON_REDEMPTION
	 ,PRO_COUPON_TYPE
	 ,PG_PRICE_MODE
	 ,PRO_PRICEMODE
	 ,ISNULL(PG_COMBOTYPE,1) AS PG_COMBOTYPE
	  FROM M_TBLPROMOTION promo
	  INNER JOIN M_TBLPROMOTION_LOC loc
	  ON promo.PRO_CODE = loc.PROL_CODE
	  INNER JOIN M_TBLPROMOTION_GROUPS gp
	  ON gp.PG_CODE = promo.PRO_GROUP
	  LEFT JOIN (SELECT DISTINCT PROE_CODE,PROE_CUSGROUPS,PROE_SUPGROUPS FROM M_TBLPROMOTION_INCLUDES ) inc
	  ON promo.PRO_CODE = inc.PROE_CODE
	  LEFT JOIN M_TBLPROMOTION_EXCLUSIONS exc
	  ON promo.PRO_CODE = exc.PROE_CODE
	  WHERE promo.PRO_STATUS=1 AND
	  convert(datetime, PRO_STDATE, 120) <= convert(datetime, cast(getdate() as date), 120) AND
   	  convert(datetime, PRO_ENDATE, 120) >= convert(datetime, cast(getdate() as date), 120) AND
	  promo.PRO_DAYS like '%'+ CONVERT(varchar,@day) +'%' AND 
	  loc.PROL_LOCCODE = @loc
	  AND PRO_COMPANYS IN (@comCode)
	  AND PG_STATUS=1
	  ORDER BY promo.PRO_PRIORITY,promo.PRO_LOYALCUSTOMERS desc

end
GO


------------------------------

ALTER             PROCEDURE [dbo].[myPOS_DP_GET_HOLD_BILL_HEADER]
@cashier varchar(max),
@loc varchar(20),
@is_signoff int
AS
BEGIN
	if (@is_signoff=0)
	begin
		SELECT INVHED_INVNO,INVHED_CASHIER,INVHED_TIME,INVHED_MODE,INVHED_NETAMT,INVHED_GROAMT,INVHED_DISPER,INVHED_MEMBER,INVHED_PRICEMODE FROM T_TBLINVHEADER_HOLD WHERE INVHED_INVOICED=0 
		AND INVHED_CANCELED=0
		AND INVHED_MODE='INV'
		AND CONVERT(DATE,INVHED_DATETIME) = CONVERT(DATE,GETDATE())
		AND INVHED_LOCCODE = @loc
		ORDER BY INVHED_INVNO
	end
	else
	begin
		SELECT INVHED_INVNO,INVHED_CASHIER,INVHED_TIME,INVHED_MODE,INVHED_NETAMT,INVHED_GROAMT,INVHED_DISPER,INVHED_MEMBER,INVHED_PRICEMODE FROM T_TBLINVHEADER_HOLD WHERE INVHED_INVOICED=0 
		AND INVHED_CANCELED=0
		AND INVHED_MODE='INV'
		AND CONVERT(DATE,INVHED_DATETIME) = CONVERT(DATE,GETDATE())
		AND INVHED_CASHIER = @cashier
		ORDER BY INVHED_INVNO
	end
	--INVHED_LOCCODE = @cashier location code is passed from the POS application to @cashier variable instead Login user, since the hold invoices should be able to recalled from any terminal
END

---------------------------



